### PR TITLE
[DNM] Lavender's notes

### PR DESCRIPTION
**Pull request by aelavender**
Some comments where students tended to get stuck or ask questions.

### CODE REVIEW

**Comment by maneesha** [comment]
@sarahelizgray @aelavender  - should this have been merged? I assumed DNM meant do not merge so I didn't do anything with it

**Comment by aelavender** [comment]
Yeah, DNM == Do Not Merge.  I think Sarah is reverting.

**Comment by sarahelizgray** [comment]
Lavender had a lot of good suggestions in her PR. Sorry DNM, didn't
register for me :(

I incorporated her suggestions in the curriculum and removed the discussion
comments directly into master since the erroneous merge was already live in
the Friday material.

**Comment by aelavender** [comment]
@sarahelizgray Some of my comments are still on the page.  This is on https://phillypythonworkshop.github.io/frisetupmac/
image

**Comment by sarahelizgray** [comment]
Whew! I think I got it!

**Pull request merged**
